packages:
  - playground
  - plugins/*
  - nuxt
  - devtools
  - test-utils
allowBuilds:
  '@ast-grep/cli': true
  '@parcel/watcher': false
  esbuild: false
  simple-git-hooks: true
  unrs-resolver: false
  '@tailwindcss/oxide': true
overrides:
  twoslash-vue: 0.3.7
  vue-router: ^5.2.0
  'nuxt@4.5.2>@nuxt/devtools': 4.0.0-alpha.15
ignoreWorkspaceRootCheck: true
shamefullyHoist: true
strictPeerDependencies: false
minimumReleaseAgeExclude:
  - '@rolldown/binding-darwin-x64@1.2.5'
  - '@rolldown/binding-linux-arm64-gnu@1.2.5'
  - devframe@0.9.6 || 0.9.8
  - '@devframes/hub@0.9.8'
  - '@devframes/hub-ui@0.9.8'
  - '@devframes/vite@0.9.8'
  - '@vitejs/devtools-kit@0.6.3'
  - '@devframes/json-render@0.9.8'
