packages:
  - playground
  - plugins/*
  - nuxt
  - devtools
  - test-utils
allowBuilds:
  '@ast-grep/cli': true
  '@parcel/watcher': false
  esbuild: false
  simple-git-hooks: true
  unrs-resolver: false
  '@tailwindcss/oxide': true
overrides:
  twoslash-vue: 0.3.7
  vue-router: ^5.0.4
ignoreWorkspaceRootCheck: true
shamefullyHoist: true
strictPeerDependencies: false
