packages:
  - playground
  - plugins/*
  - nuxt
  - devtools
  - test-utils
allowBuilds:
  '@ast-grep/cli': true
  '@parcel/watcher': false
  esbuild: false
  simple-git-hooks: true
  unrs-resolver: false
  '@tailwindcss/oxide': true
overrides:
  twoslash-vue: 0.3.9
  'nuxt@4.5.2>@nuxt/devtools': 4.0.0-alpha.18
ignoreWorkspaceRootCheck: true
shamefullyHoist: true
strictPeerDependencies: false
minimumReleaseAgeExclude:
  - '@clack/core'
  - '@clack/prompts'
  - '@devframes/*'
  - '@vitejs/devtools'
  - '@vitejs/devtools-kit'
  - devframe
  - ignore
  - srvx
  - unimport
  - vue-router@5.3.1
