/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const avatarGroupInjectionKey: typeof import('../node_modules/.pnpm/@nuxt+ui@3.0.2_@babel+parser@7.27.0_change-case@5.4.4_db0@0.3.1_embla-carousel@8.6.0_fo_dbed5a212f3bae9fad028227838ab7ae/node_modules/@nuxt/ui/dist/runtime/composables/useAvatarGroup.js')['avatarGroupInjectionKey']
  const buttonGroupInjectionKey: typeof import('../node_modules/.pnpm/@nuxt+ui@3.0.2_@babel+parser@7.27.0_change-case@5.4.4_db0@0.3.1_embla-carousel@8.6.0_fo_dbed5a212f3bae9fad028227838ab7ae/node_modules/@nuxt/ui/dist/runtime/composables/useButtonGroup.js')['buttonGroupInjectionKey']
  const defineLocale: typeof import('../node_modules/.pnpm/@nuxt+ui@3.0.2_@babel+parser@7.27.0_change-case@5.4.4_db0@0.3.1_embla-carousel@8.6.0_fo_dbed5a212f3bae9fad028227838ab7ae/node_modules/@nuxt/ui/dist/runtime/composables/defineLocale.js')['defineLocale']
  const defineShortcuts: typeof import('../node_modules/.pnpm/@nuxt+ui@3.0.2_@babel+parser@7.27.0_change-case@5.4.4_db0@0.3.1_embla-carousel@8.6.0_fo_dbed5a212f3bae9fad028227838ab7ae/node_modules/@nuxt/ui/dist/runtime/composables/defineShortcuts.js')['defineShortcuts']
  const extractShortcuts: typeof import('../node_modules/.pnpm/@nuxt+ui@3.0.2_@babel+parser@7.27.0_change-case@5.4.4_db0@0.3.1_embla-carousel@8.6.0_fo_dbed5a212f3bae9fad028227838ab7ae/node_modules/@nuxt/ui/dist/runtime/composables/defineShortcuts.js')['extractShortcuts']
  const formBusInjectionKey: typeof import('../node_modules/.pnpm/@nuxt+ui@3.0.2_@babel+parser@7.27.0_change-case@5.4.4_db0@0.3.1_embla-carousel@8.6.0_fo_dbed5a212f3bae9fad028227838ab7ae/node_modules/@nuxt/ui/dist/runtime/composables/useFormField.js')['formBusInjectionKey']
  const formFieldInjectionKey: typeof import('../node_modules/.pnpm/@nuxt+ui@3.0.2_@babel+parser@7.27.0_change-case@5.4.4_db0@0.3.1_embla-carousel@8.6.0_fo_dbed5a212f3bae9fad028227838ab7ae/node_modules/@nuxt/ui/dist/runtime/composables/useFormField.js')['formFieldInjectionKey']
  const formInputsInjectionKey: typeof import('../node_modules/.pnpm/@nuxt+ui@3.0.2_@babel+parser@7.27.0_change-case@5.4.4_db0@0.3.1_embla-carousel@8.6.0_fo_dbed5a212f3bae9fad028227838ab7ae/node_modules/@nuxt/ui/dist/runtime/composables/useFormField.js')['formInputsInjectionKey']
  const formLoadingInjectionKey: typeof import('../node_modules/.pnpm/@nuxt+ui@3.0.2_@babel+parser@7.27.0_change-case@5.4.4_db0@0.3.1_embla-carousel@8.6.0_fo_dbed5a212f3bae9fad028227838ab7ae/node_modules/@nuxt/ui/dist/runtime/composables/useFormField.js')['formLoadingInjectionKey']
  const formOptionsInjectionKey: typeof import('../node_modules/.pnpm/@nuxt+ui@3.0.2_@babel+parser@7.27.0_change-case@5.4.4_db0@0.3.1_embla-carousel@8.6.0_fo_dbed5a212f3bae9fad028227838ab7ae/node_modules/@nuxt/ui/dist/runtime/composables/useFormField.js')['formOptionsInjectionKey']
  const inputIdInjectionKey: typeof import('../node_modules/.pnpm/@nuxt+ui@3.0.2_@babel+parser@7.27.0_change-case@5.4.4_db0@0.3.1_embla-carousel@8.6.0_fo_dbed5a212f3bae9fad028227838ab7ae/node_modules/@nuxt/ui/dist/runtime/composables/useFormField.js')['inputIdInjectionKey']
  const kbdKeysMap: typeof import('../node_modules/.pnpm/@nuxt+ui@3.0.2_@babel+parser@7.27.0_change-case@5.4.4_db0@0.3.1_embla-carousel@8.6.0_fo_dbed5a212f3bae9fad028227838ab7ae/node_modules/@nuxt/ui/dist/runtime/composables/useKbd.js')['kbdKeysMap']
  const localeContextInjectionKey: typeof import('../node_modules/.pnpm/@nuxt+ui@3.0.2_@babel+parser@7.27.0_change-case@5.4.4_db0@0.3.1_embla-carousel@8.6.0_fo_dbed5a212f3bae9fad028227838ab7ae/node_modules/@nuxt/ui/dist/runtime/composables/useLocale.js')['localeContextInjectionKey']
  const useAppConfig: typeof import('../node_modules/.pnpm/@nuxt+ui@3.0.2_@babel+parser@7.27.0_change-case@5.4.4_db0@0.3.1_embla-carousel@8.6.0_fo_dbed5a212f3bae9fad028227838ab7ae/node_modules/@nuxt/ui/dist/runtime/vue/composables/useAppConfig.js')['useAppConfig']
  const useAvatarGroup: typeof import('../node_modules/.pnpm/@nuxt+ui@3.0.2_@babel+parser@7.27.0_change-case@5.4.4_db0@0.3.1_embla-carousel@8.6.0_fo_dbed5a212f3bae9fad028227838ab7ae/node_modules/@nuxt/ui/dist/runtime/composables/useAvatarGroup.js')['useAvatarGroup']
  const useButtonGroup: typeof import('../node_modules/.pnpm/@nuxt+ui@3.0.2_@babel+parser@7.27.0_change-case@5.4.4_db0@0.3.1_embla-carousel@8.6.0_fo_dbed5a212f3bae9fad028227838ab7ae/node_modules/@nuxt/ui/dist/runtime/composables/useButtonGroup.js')['useButtonGroup']
  const useComponentIcons: typeof import('../node_modules/.pnpm/@nuxt+ui@3.0.2_@babel+parser@7.27.0_change-case@5.4.4_db0@0.3.1_embla-carousel@8.6.0_fo_dbed5a212f3bae9fad028227838ab7ae/node_modules/@nuxt/ui/dist/runtime/composables/useComponentIcons.js')['useComponentIcons']
  const useContentSearch: typeof import('../node_modules/.pnpm/@nuxt+ui-pro@3.0.2_@babel+parser@7.27.0_change-case@5.4.4_db0@0.3.1_embla-carousel@8.6._ff991e71bf47b458df0d2e806b2a1895/node_modules/@nuxt/ui-pro/dist/runtime/composables/useContentSearch.js')['useContentSearch']
  const useFormField: typeof import('../node_modules/.pnpm/@nuxt+ui@3.0.2_@babel+parser@7.27.0_change-case@5.4.4_db0@0.3.1_embla-carousel@8.6.0_fo_dbed5a212f3bae9fad028227838ab7ae/node_modules/@nuxt/ui/dist/runtime/composables/useFormField.js')['useFormField']
  const useKbd: typeof import('../node_modules/.pnpm/@nuxt+ui@3.0.2_@babel+parser@7.27.0_change-case@5.4.4_db0@0.3.1_embla-carousel@8.6.0_fo_dbed5a212f3bae9fad028227838ab7ae/node_modules/@nuxt/ui/dist/runtime/composables/useKbd.js')['useKbd']
  const useLocale: typeof import('../node_modules/.pnpm/@nuxt+ui@3.0.2_@babel+parser@7.27.0_change-case@5.4.4_db0@0.3.1_embla-carousel@8.6.0_fo_dbed5a212f3bae9fad028227838ab7ae/node_modules/@nuxt/ui/dist/runtime/composables/useLocale.js')['useLocale']
  const useLocalePro: typeof import('../node_modules/.pnpm/@nuxt+ui-pro@3.0.2_@babel+parser@7.27.0_change-case@5.4.4_db0@0.3.1_embla-carousel@8.6._ff991e71bf47b458df0d2e806b2a1895/node_modules/@nuxt/ui-pro/dist/runtime/composables/useLocalePro.js')['useLocalePro']
  const useOverlay: typeof import('../node_modules/.pnpm/@nuxt+ui@3.0.2_@babel+parser@7.27.0_change-case@5.4.4_db0@0.3.1_embla-carousel@8.6.0_fo_dbed5a212f3bae9fad028227838ab7ae/node_modules/@nuxt/ui/dist/runtime/composables/useOverlay.js')['useOverlay']
  const useResizable: typeof import('../node_modules/.pnpm/@nuxt+ui-pro@3.0.2_@babel+parser@7.27.0_change-case@5.4.4_db0@0.3.1_embla-carousel@8.6._ff991e71bf47b458df0d2e806b2a1895/node_modules/@nuxt/ui-pro/dist/runtime/composables/useResizable.js')['useResizable']
  const useScrollspy: typeof import('../node_modules/.pnpm/@nuxt+ui-pro@3.0.2_@babel+parser@7.27.0_change-case@5.4.4_db0@0.3.1_embla-carousel@8.6._ff991e71bf47b458df0d2e806b2a1895/node_modules/@nuxt/ui-pro/dist/runtime/composables/useScrollspy.js')['useScrollspy']
  const useToast: typeof import('../node_modules/.pnpm/@nuxt+ui@3.0.2_@babel+parser@7.27.0_change-case@5.4.4_db0@0.3.1_embla-carousel@8.6.0_fo_dbed5a212f3bae9fad028227838ab7ae/node_modules/@nuxt/ui/dist/runtime/composables/useToast.js')['useToast']
}
// for type re-export
declare global {
  // @ts-ignore
  export type { UseResizableProps, UseResizableReturn } from '../node_modules/.pnpm/@nuxt+ui-pro@3.0.2_@babel+parser@7.27.0_change-case@5.4.4_db0@0.3.1_embla-carousel@8.6._ff991e71bf47b458df0d2e806b2a1895/node_modules/@nuxt/ui-pro/dist/runtime/composables/useResizable.d'
  import('../node_modules/.pnpm/@nuxt+ui-pro@3.0.2_@babel+parser@7.27.0_change-case@5.4.4_db0@0.3.1_embla-carousel@8.6._ff991e71bf47b458df0d2e806b2a1895/node_modules/@nuxt/ui-pro/dist/runtime/composables/useResizable.d')
  // @ts-ignore
  export type { ShortcutConfig, ShortcutsConfig, ShortcutsOptions } from '../node_modules/.pnpm/@nuxt+ui@3.0.2_@babel+parser@7.27.0_change-case@5.4.4_db0@0.3.1_embla-carousel@8.6.0_fo_dbed5a212f3bae9fad028227838ab7ae/node_modules/@nuxt/ui/dist/runtime/composables/defineShortcuts.d'
  import('../node_modules/.pnpm/@nuxt+ui@3.0.2_@babel+parser@7.27.0_change-case@5.4.4_db0@0.3.1_embla-carousel@8.6.0_fo_dbed5a212f3bae9fad028227838ab7ae/node_modules/@nuxt/ui/dist/runtime/composables/defineShortcuts.d')
  // @ts-ignore
  export type { UseComponentIconsProps } from '../node_modules/.pnpm/@nuxt+ui@3.0.2_@babel+parser@7.27.0_change-case@5.4.4_db0@0.3.1_embla-carousel@8.6.0_fo_dbed5a212f3bae9fad028227838ab7ae/node_modules/@nuxt/ui/dist/runtime/composables/useComponentIcons.d'
  import('../node_modules/.pnpm/@nuxt+ui@3.0.2_@babel+parser@7.27.0_change-case@5.4.4_db0@0.3.1_embla-carousel@8.6.0_fo_dbed5a212f3bae9fad028227838ab7ae/node_modules/@nuxt/ui/dist/runtime/composables/useComponentIcons.d')
  // @ts-ignore
  export type { KbdKey, KbdKeySpecific } from '../node_modules/.pnpm/@nuxt+ui@3.0.2_@babel+parser@7.27.0_change-case@5.4.4_db0@0.3.1_embla-carousel@8.6.0_fo_dbed5a212f3bae9fad028227838ab7ae/node_modules/@nuxt/ui/dist/runtime/composables/useKbd.d'
  import('../node_modules/.pnpm/@nuxt+ui@3.0.2_@babel+parser@7.27.0_change-case@5.4.4_db0@0.3.1_embla-carousel@8.6.0_fo_dbed5a212f3bae9fad028227838ab7ae/node_modules/@nuxt/ui/dist/runtime/composables/useKbd.d')
  // @ts-ignore
  export type { OverlayOptions, Overlay } from '../node_modules/.pnpm/@nuxt+ui@3.0.2_@babel+parser@7.27.0_change-case@5.4.4_db0@0.3.1_embla-carousel@8.6.0_fo_dbed5a212f3bae9fad028227838ab7ae/node_modules/@nuxt/ui/dist/runtime/composables/useOverlay.d'
  import('../node_modules/.pnpm/@nuxt+ui@3.0.2_@babel+parser@7.27.0_change-case@5.4.4_db0@0.3.1_embla-carousel@8.6.0_fo_dbed5a212f3bae9fad028227838ab7ae/node_modules/@nuxt/ui/dist/runtime/composables/useOverlay.d')
  // @ts-ignore
  export type { Toast } from '../node_modules/.pnpm/@nuxt+ui@3.0.2_@babel+parser@7.27.0_change-case@5.4.4_db0@0.3.1_embla-carousel@8.6.0_fo_dbed5a212f3bae9fad028227838ab7ae/node_modules/@nuxt/ui/dist/runtime/composables/useToast.d'
  import('../node_modules/.pnpm/@nuxt+ui@3.0.2_@babel+parser@7.27.0_change-case@5.4.4_db0@0.3.1_embla-carousel@8.6.0_fo_dbed5a212f3bae9fad028227838ab7ae/node_modules/@nuxt/ui/dist/runtime/composables/useToast.d')
}
