/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ICarbonArrowLeft: typeof import('~icons/carbon/arrow-left')['default']
    ICarbonCheckmark: typeof import('~icons/carbon/checkmark')['default']
    ICarbonClose: typeof import('~icons/carbon/close')['default']
    ICarbonIntentRequestInactive: typeof import('~icons/carbon/intent-request-inactive')['default']
    ICarbonLoading: typeof import('~icons/carbon/loading')['default']
    ICarbonMaximize: typeof import('~icons/carbon/maximize')['default']
    ICarbonMinimize: typeof import('~icons/carbon/minimize')['default']
    ICarbonPopup: typeof import('~icons/carbon/popup')['default']
    ICarbonSearch: typeof import('~icons/carbon/search')['default']
    ICarbonTrashCan: typeof import('~icons/carbon/trash-can')['default']
    ICarbonWarning: typeof import('~icons/carbon/warning')['default']
    ListQueryEntry: typeof import('./src/panel/components/ListQueryEntry.vue')['default']
    PiPContainer: typeof import('./src/panel/components/PiPContainer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UButton: typeof import('./src/panel/components/UButton.ce.vue')['default']
    'UButton.ce': typeof import('./src/panel/components/UButton.ce.vue')['default']
    UCollapse: typeof import('./src/panel/components/UCollapse.ce.vue')['default']
    'UCollapse.ce': typeof import('./src/panel/components/UCollapse.ce.vue')['default']
    UCollapsible: typeof import('./src/panel/components/UCollapsible.vue')['default']
    UInput: typeof import('./src/panel/components/UInput.ce.vue')['default']
    'UInput.ce': typeof import('./src/panel/components/UInput.ce.vue')['default']
  }
}
