/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ICarbonClose: typeof import('~icons/carbon/close')['default']
    ICarbonMaximize: typeof import('~icons/carbon/maximize')['default']
    ICarbonMinimize: typeof import('~icons/carbon/minimize')['default']
    ICarbonPopup: typeof import('~icons/carbon/popup')['default']
    ICarbonSearch: typeof import('~icons/carbon/search')['default']
    ICarbonTrashCan: typeof import('~icons/carbon/trash-can')['default']
    PiPContainer: typeof import('./src/panel/components/PiPContainer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    'UButton.ce': typeof import('./src/panel/components/UButton.ce.vue')['default']
    UInput: typeof import('./src/panel/components/UInput.ce.vue')['default']
    'UInput.ce': typeof import('./src/panel/components/UInput.ce.vue')['default']
  }
}
