/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UApp: typeof import('./../node_modules/.pnpm/@nuxt+ui@3.0.2_@babel+parser@7.27.0_change-case@5.4.4_db0@0.3.1_embla-carousel@8.6.0_fo_dbed5a212f3bae9fad028227838ab7ae/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UButton: typeof import('./../node_modules/.pnpm/@nuxt+ui@3.0.2_@babel+parser@7.27.0_change-case@5.4.4_db0@0.3.1_embla-carousel@8.6.0_fo_dbed5a212f3bae9fad028227838ab7ae/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UColorModeButton: typeof import('./../node_modules/.pnpm/@nuxt+ui-pro@3.0.2_@babel+parser@7.27.0_change-case@5.4.4_db0@0.3.1_embla-carousel@8.6._ff991e71bf47b458df0d2e806b2a1895/node_modules/@nuxt/ui-pro/dist/runtime/vue/components/color-mode/ColorModeButton.vue')['default']
    UContainer: typeof import('./../node_modules/.pnpm/@nuxt+ui@3.0.2_@babel+parser@7.27.0_change-case@5.4.4_db0@0.3.1_embla-carousel@8.6.0_fo_dbed5a212f3bae9fad028227838ab7ae/node_modules/@nuxt/ui/dist/runtime/components/Container.vue')['default']
    UFooter: typeof import('./../node_modules/.pnpm/@nuxt+ui-pro@3.0.2_@babel+parser@7.27.0_change-case@5.4.4_db0@0.3.1_embla-carousel@8.6._ff991e71bf47b458df0d2e806b2a1895/node_modules/@nuxt/ui-pro/dist/runtime/components/Footer.vue')['default']
    UHeader: typeof import('./../node_modules/.pnpm/@nuxt+ui-pro@3.0.2_@babel+parser@7.27.0_change-case@5.4.4_db0@0.3.1_embla-carousel@8.6._ff991e71bf47b458df0d2e806b2a1895/node_modules/@nuxt/ui-pro/dist/runtime/components/Header.vue')['default']
    ULink: typeof import('./../node_modules/.pnpm/@nuxt+ui@3.0.2_@babel+parser@7.27.0_change-case@5.4.4_db0@0.3.1_embla-carousel@8.6.0_fo_dbed5a212f3bae9fad028227838ab7ae/node_modules/@nuxt/ui/dist/runtime/vue/components/Link.vue')['default']
    ULinkBase: typeof import('./../node_modules/.pnpm/@nuxt+ui@3.0.2_@babel+parser@7.27.0_change-case@5.4.4_db0@0.3.1_embla-carousel@8.6.0_fo_dbed5a212f3bae9fad028227838ab7ae/node_modules/@nuxt/ui/dist/runtime/components/LinkBase.vue')['default']
    UMain: typeof import('./../node_modules/.pnpm/@nuxt+ui-pro@3.0.2_@babel+parser@7.27.0_change-case@5.4.4_db0@0.3.1_embla-carousel@8.6._ff991e71bf47b458df0d2e806b2a1895/node_modules/@nuxt/ui-pro/dist/runtime/components/Main.vue')['default']
    USeparator: typeof import('./../node_modules/.pnpm/@nuxt+ui@3.0.2_@babel+parser@7.27.0_change-case@5.4.4_db0@0.3.1_embla-carousel@8.6.0_fo_dbed5a212f3bae9fad028227838ab7ae/node_modules/@nuxt/ui/dist/runtime/components/Separator.vue')['default']
  }
}
