/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/mutations': RouteRecordInfo<
      '/mutations',
      '/mutations',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/queries': RouteRecordInfo<
      '/queries',
      '/queries',
      Record<never, never>,
      Record<never, never>,
      | '/queries/(unselected)'
      | '/queries/[queryId]'
    >,
    '/queries/(unselected)': RouteRecordInfo<
      '/queries/(unselected)',
      '/queries',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/queries/[queryId]': RouteRecordInfo<
      '/queries/[queryId]',
      '/queries/:queryId',
      { queryId: ParamValue<true> },
      { queryId: ParamValue<false> },
      | never
    >,
    '/settings': RouteRecordInfo<
      '/settings',
      '/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/panel/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/panel/pages/mutations.vue': {
      routes:
        | '/mutations'
      views:
        | never
    }
    'src/panel/pages/queries.vue': {
      routes:
        | '/queries'
        | '/queries/(unselected)'
        | '/queries/[queryId]'
      views:
        | 'default'
    }
    'src/panel/pages/queries/(unselected).vue': {
      routes:
        | '/queries/(unselected)'
      views:
        | never
    }
    'src/panel/pages/queries/[queryId].vue': {
      routes:
        | '/queries/[queryId]'
      views:
        | never
    }
    'src/panel/pages/settings.vue': {
      routes:
        | '/settings'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
