name: ci

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - 'docs/**'
    # We don't need to test tags
    tags-ignore:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v6
      - uses: actions/setup-node@v6
        with:
          node-version: lts/*
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Prepare Nuxt
        run: pnpm -C nuxt run dev:prepare
      - name: Lint
        run: pnpm run lint
      - name: Build
        run: pnpm run build
      - name: Build all packages
        run: pnpm run build:all
      - name: Test with coverage
        run: pnpm run test:cov
      - name: Type tests
        run: pnpm run test:types
      - name: Size check
        run: pnpm run size
      - name: Codemods tests
        run: pnpm run codemods:test
      # avoid updating deps that do not build docs
      - name: Build docs
        run: pnpm run docs:build

      - uses: codecov/codecov-action@v6
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
